version: '3.8'

services:
  backend:
    build: ./backend
    container_name: devops_backend
    ports:
      - "5000:5000"
    # Root .env එකේ තියෙන සියලුම දත්ත මෙතැනින් Backend කන්ටේනරයට ලබා දේ
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      # Build වෙන වෙලාවේදී VITE_API_URL එක ලබා දීම
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: devops_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
