# ඔයාගේ Organization නම පහතින් දාන්න
sonar.organization=madupadilshan
# ඔයාගේ Project Key එක පහතින් දාන්න
sonar.projectKey=madupadilshan_mern-devops-practice

# අපි ස්කෑන් කරන්න ඕන ෆෝල්ඩර මොනවද කියලා මෙතනින් කියනවා
sonar.sources=backend/src,frontend/src
